/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.testevr.view;

import com.testevr.controller.EstoqueController;
import com.testevr.controller.ProdutoController;
import com.testevr.model.EstoqueModel;
import com.testevr.model.ProdutoModel;
import com.testevr.util.FormatarValor;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 * @author Diego Barbosa
 */
public class ProdutoView extends javax.swing.JFrame {

    // Data
    Locale localeBR = new Locale("pt", "BR");
    NumberFormat valorReal = NumberFormat.getCurrencyInstance(localeBR);

    // Produto
    ProdutoModel produtoModel = new ProdutoModel();
    ProdutoController produtoController = new ProdutoController();
    
    // Estoque
    EstoqueModel estoqueModel = new EstoqueModel();
    EstoqueController estoqueController = new EstoqueController();

    // Tela
    private MainView mainView;

    /**
     * Creates new form CursoView
     */
    public ProdutoView(MainView mainView) {
        initComponents();
        this.mainView = mainView;
    }

    public ProdutoView() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSalvarProduto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jtfIdProduto = new javax.swing.JTextField();
        jtfNomeProduto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCancelarProduto = new javax.swing.JButton();
        jtfValorProduto = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtfCodigoEAN = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produto");
        setResizable(false);

        btnSalvarProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnSalvarProduto.setText("Salvar");
        btnSalvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarProdutoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("ID:");

        jtfIdProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfIdProduto.setEnabled(false);
        jtfIdProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIdProdutoActionPerformed(evt);
            }
        });

        jtfNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jtfNomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfNomeProdutoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Preço:");

        btnCancelarProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        btnCancelarProduto.setText("Cancelar");
        btnCancelarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarProdutoActionPerformed(evt);
            }
        });

        jtfValorProduto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jtfValorProduto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Código EAN:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("(Opcional)");

        jtfCodigoEAN.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jtfCodigoEAN.setFont(new java.awt.Font("Noto Sans", 0, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jtfIdProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jtfNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(jtfCodigoEAN, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jtfValorProduto))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtfNomeProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jtfIdProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtfValorProduto)
                    .addComponent(jtfCodigoEAN, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarProdutoActionPerformed
        if (mainView.editarSalvar.equals("salvar")) {
            salvarProduto();
            mainView.setEnabled(true);
        } else if (mainView.editarSalvar.equals("editar")) {
            editarProduto();
        }
    }//GEN-LAST:event_btnSalvarProdutoActionPerformed

    private void jtfIdProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIdProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIdProdutoActionPerformed

    private void jtfNomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfNomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfNomeProdutoActionPerformed

    private void btnCancelarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarProdutoActionPerformed
        dispose();
        mainView.setEnabled(true);
    }//GEN-LAST:event_btnCancelarProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProdutoView().setVisible(true);
            }
        });
    }

    private void salvarProduto() {
        if (jtfNomeProduto.getText().isEmpty() || jtfValorProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else if (jtfNomeProduto.getText().length() >= 151) {
            JOptionPane.showMessageDialog(null, "Campo descrição excede o limite de 150 caracteres!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            produtoModel.setDescricaoProduto(jtfNomeProduto.getText().toUpperCase());
            produtoModel.setValorProduto(FormatarValor.formatarStringDouble(jtfValorProduto.getText()));
            produtoModel.setCodigoEAN(jtfCodigoEAN.getText().toString());
            if (produtoController.salvarProdutoController(produtoModel) > 0) {
                estoqueModel.setProduto(produtoModel);
                estoqueController.salvarEstoqueController(estoqueModel);
                JOptionPane.showMessageDialog(null, "Produto cadastrado com sucesso", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
                mainView.listarProdutos();
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Produto não cadastrado", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    private void editarProduto() {
        if (jtfNomeProduto.getText().isEmpty() || jtfValorProduto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Campo vazio!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else if (jtfNomeProduto.getText().length() >= 150) {
            JOptionPane.showMessageDialog(null, "Campo descrição excede o limite de 150 caracteres!", "ATENÇÃO",
                    JOptionPane.WARNING_MESSAGE);
        } else {
            produtoModel.setDescricaoProduto(jtfNomeProduto.getText().toUpperCase());
            produtoModel.setValorProduto(FormatarValor.formatarStringDouble(jtfValorProduto.getText()));
            produtoModel.setCodigoEAN(jtfCodigoEAN.getText().toString());
            if (produtoController.atualizarProdutoController(produtoModel)) {
                JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
                mainView.listarProdutos();
                dispose();
                mainView.setEnabled(true);
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível atualizar o produto", "ATENÇÃO",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }

    public void setProdutoModel(ProdutoModel produto) {
        this.produtoModel = produto;
        jtfIdProduto.setText(this.produtoModel.getCodigoProduto().toString());
        jtfNomeProduto.setText(this.produtoModel.getDescricaoProduto());
        jtfValorProduto.setText(produtoModel.getValorProduto().toString());
        jtfCodigoEAN.setText(this.produtoModel.getCodigoEAN());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarProduto;
    private javax.swing.JButton btnSalvarProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField jtfCodigoEAN;
    private javax.swing.JTextField jtfIdProduto;
    private javax.swing.JTextField jtfNomeProduto;
    private javax.swing.JFormattedTextField jtfValorProduto;
    // End of variables declaration//GEN-END:variables
}
